### PR TITLE
Update endpoint from get-available-version to get-available-versions

### PR DESCRIPTION
**Pull request by koliwbr**
https://updater.factorio.com/get-available-versions

### CODE REVIEW

**Comment by Artentus** [comment]
get-available-versions is working just fine

**Comment by koliwbr** [comment]
> get-available-versions is working just fine
miss type in title, i mean other way. 

https://updater.factorio.com/get-available-version 404
https://updater.factorio.com/get-available-versions OK

image

**Comment by Artentus** [comment]
Huh, this is weird. 
Firstly, this fix had been submitted a long time ago, but apparently I never updated the deployed website.  
And second, your PR actually changes it back to get-available-version.

I haven't rebuilt this thing in 4 years, I hope I can still do it lol.

**Comment by koliwbr** [comment]
I wrote it month ago, probably on 3.0 AM :-)

**Comment by Artentus** [comment]
It's updated now

**Pull request closed without merging**
